version: 2
jobs:
  build:
    docker:
      - image: yoangrigorov/glagol-dsl-builds:latest
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${CIRCLE_TAG}-SNAPSHOT
      - run: mvn package
      - run:
          name: Making a GitHub Release
          command: |
            if [[ ! -z ${CIRCLE_TAG} ]]; then github-release release --user bulgariaphp --repo glagol-dsl-client --tag ${CIRCLE_TAG} --name "${CIRCLE_TAG}" --description "Release ${CIRCLE_TAG}"; fi; \
            if [[ ! -z ${CIRCLE_TAG} ]]; then github-release upload --user bulgariaphp --repo glagol-dsl-client --tag ${CIRCLE_TAG} --name "glagol-dsl-client-${CIRCLE_TAG}.jar" --file target/glagol-dsl-client-${CIRCLE_TAG}-SNAPSHOT.jar; fi
      - run:
          name: Publishing Docker Hub images
          command: |
            cp target/glagol-dsl-client-${CIRCLE_TAG}-SNAPSHOT.jar docker/glagol-dsl-client.jar
            TAG="dev-master"
            if [[ ! -z ${CIRCLE_TAG} ]]; then TAG=${CIRCLE_TAG}; fi
            docker build -t glagol/client:${TAG} -t glagol/client:latest docker/
            docker login -u ${DOCKER_ID} -p ${DOCKER_SECRET}
            docker push glagol/client:${TAG}
            if [[ ! -z ${CIRCLE_TAG} ]]; then \
              TAG=${TAG:0:3}; \
              docker build -t glagol/client:${TAG} docker/ ; \
              docker push glagol/client:${TAG}; \
              docker push glagol/client:latest; \
            fi
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^ignore-.*/