version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${CIRCLE_TAG}-SNAPSHOT
      - run: mvn package
      - run: sudo apt-get -y install golang
      - run: mkdir .go
      - run: export GOPATH=$(pwd)/.go && go get github.com/aktau/github-release
      - run: .go/bin/github-releases -h
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^ignore-.*/